### ISSUE TITLE
Style.css should not be versioned if it is autogenerated

### ISSUE THREAD

**Issue by KrzysztofMadejski** [WhiteHouse/playbook#131]

**Comment by jhfrench** [comment]
I think you're refering to `assets/css/styles.css`; if so, I agree. Including `styles.css` within the sourcecode invites developers to edit the file directly (particularly developers who don't read instructions in the README.md).

**Comment by cew821** [comment]
@benbalter curious to get your take on this. We are doing deploys based on this repository, from Github pages, so I'm not sure removing the .css file would work for us.

**Comment by benbalter** [comment]
@cew821 yes and no. @jhfrench is correct that it is the rendered CSS (rather than the source Sass) and is traditionally not checked into version control for the reasons mentioned (you'd never edit the generated version). Since you're using GitHub pages, however, as currently configured, it needs to be checked in.

That said, the smarter way would be to use Jekyll's native Sass functionality, to store the source file, and generate the resulting CSS on push. If you'd like, it's an easy fix, I can send a pull request your way?

**Comment by cew821** [comment]
Thanks @benbalter for the pointer, I didn't know Jekyll could auto-generate CSS. Thanks @KrzysztofMadejski for flagging the issue.

:muscle: :computer: :us:

**Comment by KrzysztofMadejski** [comment]
Thank you, I've learned something today as well. :)

**Comment by jhfrench** [comment]
My initial instinct was to disagree with this issue--to argue *for* including the generated CSS. I was going to use jQuery's `jQuery.js` file as an example of versioning both the source and the compiled result file...but [jQuery's Git project](https://github.com/jquery/jquery) *doesn't* version jQuery.js (or jQuery.min.js). Their build kicks off distribution of the compiled file to the many CDNs. Essentially, they've decoupled versioning from distribution.
