### ISSUE TITLE
Play 8, Open Source problems with SCRM

### ISSUE THREAD

**Issue by jerome-mcnamara** [WhiteHouse/playbook#135]
Play 8, "Choose a modern technology stack" creates conflicts when it suggests agencies use open source.  Supply Chain Risk Management (http://csrc.nist.gov/scrm/) prevents Federal systems from using HW, SW, or development work from people hostile to the U.S. (i.e., China, or its citizens).  Are there too many opportunities for embedding malicious code with an open source strategy?

**Comment by jhfrench** [comment]
One man's opinion: there are many opportunities *to attempt* embedding malicious code, but open source (as opposed to walled-garden development) allows more and better mechanisms for identifying and preventing that malicious code. Consider, as anecdotal evidence, the scrutiny [this documentation change has received](https://github.com/jquery/api.jquery.com/pull/740). This scrutiny is 1) representative of open-source workflow, and 2) appropriate.

**Comment by cew821** [comment]
Hi @jerome-mcnamara - thanks for the note. You raise a good question, and luckily the Department of Defense has thought through a lot of these issues in detail.

I encourage you to read through [DoD's Open Source FAQs](http://dodcio.defense.gov/OpenSourceSoftwareFAQ.aspx), which cites several memorandum and other policies that try to address some common misconceptions about the use of Open Source software in the Department of Defense and the rest of the government.

Because open source code is, by definition, available for everyone to read and analyze before it is used, the opportunities for malicious code to be inserted without the knowledge of the consumers of that software is greatly reduced. Or, as the Department of Defense says:

> To effectively achieve its missions, the Department of Defense must develop and
update its software-based capabilities faster than ever, to anticipate new threats and
respond to continuously changing requirements. The use of Open Source Software
(OSS) can provide advantages in this regard.

**Comment by jerome-mcnamara** [comment]
I'd like to thank the 2 persons above for their insight.  Open Source is not my area of expertise but I had to pose my concern and I appreciate the feedback and discussion.
